# Use the official Python image
FROM python:3.12

# Set the working directory
WORKDIR /app

# Copy the server script into the container
COPY server.py .

# Expose the port the server will listen on
EXPOSE 5001

# Command to run the server
CMD ["python3", "server.py"]
