# Use the official Python image
FROM python:3.12

# Set the working directory
WORKDIR /app

# Copy the client script into the container
COPY client.py .

EXPOSE 5001
# Command to run the client
ENTRYPOINT ["python3", "client.py"]

